spring:
  kafka:
    bootstrap-servers: kafka1:19092
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://mysql:3306/subscription_db
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
course:
  url: http://courses:8080/
  path: courses

student:
  url: http://students:8080/
  path: students
