spring:
  kafka:
    bootstrap-servers: kafka1:19092
    consumer:
      bootstrap-servers: kafka1:19092
    producer:
      bootstrap-servers: kafka1:19092
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://mysql:3306/course_db
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/course_db
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
