CREATE TABLE COURSES
(
    ID         INT PRIMARY KEY,
    CREATED_AT TIMESTAMP
);

CREATE TABLE STUDENTS
(
    ID         INT PRIMARY KEY,
    CREATED_AT TIMESTAMP
);

CREATE TABLE SUBSCRIPTIONS
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    COURSE_ID  INT,
    STUDENT_ID INT,
    CREATED_AT TIMESTAMP,
    UNIQUE (COURSE_ID, STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID)
);

CREATE INDEX COURSE_ID_IDX
    ON SUBSCRIPTIONS (COURSE_ID);

CREATE INDEX STUDENT_ID_IDX
    ON SUBSCRIPTIONS (STUDENT_ID);