CREATE TABLE STUDENTS
(
    ID               INT AUTO_INCREMENT PRIMARY KEY,
    NAME             VARCHAR(45),
    STATE            VARCHAR(45),
    CREATED_AT       TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP
);
